apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgres-uid
    url: postgres:5432
    database: grafana_db
    user: grafana_user
    secureJsonData:
      password: grafana_password
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    isDefault: false
    editable: true
